version: '3'

services:
  nginx:
    image: nginx:1.22.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - images:/application/frontend/static/images/hotels/
      - static:/static

  redis:
    image: redis:7.2-alpine
    restart: always

    volumes:
      - redis-data:/var/lib/redis
      - redis-data:/usr/local/etc/redis/redis.conf 
    env_file: .env

  postgres:
    image: postgres:16.1-alpine3.18
    restart: always
    

    volumes:
      - db-data:/var/lib/postgresql/data

  api:
    build:
      context: ./application
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on: 
      - postgres
      - redis
    volumes:
      - images:/application/frontend/static/images/hotels/
      - static:/static


  celery:
    build:
      context: ./application
      dockerfile: Dockerfile_celery
    env_file:
      - .env
    depends_on: 
      - api
 
  celery_beat:
    build:
      context: ./application
      dockerfile: Dockerfile_celery_beat
    env_file:
      - .env
    depends_on: 
      - api

  flower:
    build:
      context: ./application
      dockerfile: Dockerfile_flower
    env_file:
      - .env
    depends_on: 
      - api

    

volumes:
  db-data:
  pgadmin:
  redis-data:
  images:
  static: