"""alembic v2

Revision ID: 1935421deca4
Revises: 3d371eb1d67b
Create Date: 2024-01-25 21:20:39.918298

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1935421deca4"
down_revision: Union[str, None] = "3d371eb1d67b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("bookings_room_id_fkey", "bookings", type_="foreignkey")
    op.drop_constraint("bookings_user_id_fkey", "bookings", type_="foreignkey")
    op.alter_column(
        "hotels",
        "services",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "hotels", "image_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "rooms", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "rooms",
        "services",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=False,
    )
    op.alter_column(
        "rooms", "quantity", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "rooms", "image_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.alter_column(
        "rooms", "image_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "rooms", "quantity", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "rooms",
        "services",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.alter_column(
        "rooms", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "hotels", "image_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "hotels",
        "services",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        nullable=True,
    )
    op.create_foreign_key(
        "bookings_user_id_fkey", "bookings", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "bookings_room_id_fkey", "bookings", "rooms", ["room_id"], ["id"]
    )
    # ### end Alembic commands ###
