"""User authorize

Revision ID: 9d6126e7bd33
Revises: e83a555bc9eb
Create Date: 2024-02-22 16:14:27.869962

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9d6126e7bd33'
down_revision: Union[str, None] = 'e83a555bc9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authority', sa.Enum('user', 'moderator', 'admin', native_enum=False), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'authority')
    # ### end Alembic commands ###
